In [70]:
import pandas as pd
from pathlib import Path

### Import data (sales_tables) from raw .csv files

In [71]:
df_01_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.01.csv')
df_02_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.02.csv')
df_03_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.03.csv')
df_04_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.04.csv')
df_05_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.05.csv')
df_06_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.06.csv')
df_07_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.07.csv')

In [72]:
df_01_06['Период'] = '01.06.2026'
df_02_06['Период'] = '02.06.2026'
df_03_06['Период'] = '03.06.2026'
df_04_06['Период'] = '04.06.2026'
df_05_06['Период'] = '05.06.2026'
df_06_06['Период'] = '06.06.2026'
df_07_06['Период'] = '07.06.2026'

In [73]:
df_01_06.dtypes

Тип                     str
Название позиции        str
Продано               int64
Цена                float64
Период                  str
Location                str
dtype: object

In [74]:
dfs = [df_01_06, df_02_06, df_03_06, df_04_06, df_05_06, df_06_06, df_07_06]

In [75]:
sales = pd.concat(dfs, ignore_index=True)

In [76]:
sales

,Тип,Название позиции,Продано,Цена,Период,Location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI

### Data cleaning (Sales Table)

In [77]:
sales = sales.rename(columns={
    'Тип': 'type',
    'Название позиции': 'name',
    'Продано': 'qty',
    'Цена': 'sum',
    'Период': 'date',
    'Location': 'location'
    })

In [78]:
sales

,type,name,qty,sum,date,location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI

In [79]:
sales['price'] = sales['sum'] / sales['qty']

In [80]:
sales['date'] = pd.to_datetime(sales['date'], format='%d.%m.%Y')

In [81]:
sales.dtypes

type                   str
name                   str
qty                  int64
sum                float64
date        datetime64[us]
location               str
price              float64
dtype: object

In [82]:
sales

,type,name,qty,sum,date,location,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,VIBE SUSHI,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,VIBE SUSHI,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,VIBE SUSHI,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,VIBE SUSHI,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,VIBE SUSHI,45.0
...,...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,2026-06-07,VIBE SUSHI,1.5
187,Дополнение,Wasabi,2,4.0,2026-06-07,VIBE SUSHI,2.0
188,Дополнение,Sos teriyaki 30ml,1,3.0,2026-06-07,VIBE SUSHI,3.0
189,Дополнение,Krabs - Burger,1,25.0,2026-06-07,VIBE SUSHI,25.0
190,Дополнение,6 szt,1,NaN,2026-06-07,VIBE SUSHI,NaN

In [83]:
sales = sales.drop(labels=['location'], axis=1)

In [84]:
sales

,type,name,qty,sum,date,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,45.0
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,2026-06-07,1.5
187,Дополнение,Wasabi,2,4.0,2026-06-07,2.0
188,Дополнение,Sos teriyaki 30ml,1,3.0,2026-06-07,3.0
189,Дополнение,Krabs - Burger,1,25.0,2026-06-07,25.0
190,Дополнение,6 szt,1,NaN,2026-06-07,NaN

In [85]:
sales = sales[sales['type'] != 'Дополнение']

In [86]:
sales

,type,name,qty,sum,date,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,45.0
...,...,...,...,...,...,...
179,Позиция,Miso z łososiem | 350 ml,1,35.0,2026-06-07,35.0
180,Позиция,Futomaki FIRE HARMONY | 6 szt,1,58.0,2026-06-07,58.0
181,Позиция,Hosomaki AWOKADO | 8 szt,1,21.0,2026-06-07,21.0
182,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt,1,38.0,2026-06-07,38.0
183,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,2026-06-07,36.0

In [87]:
sales = sales[['date', 'name', 'qty', 'price', 'sum']]

In [88]:
sales

          date                                    name  qty  price    sum
0   2026-06-01       Futomaki ŁOSOŚ GRILLOWANY | 6 szt    6   38.0  228.0
1   2026-06-01                    Nigiri łosoś | 2 szt    4   25.0  100.0
2   2026-06-01               PROMO 1+1=3 Sushi burgery    3  120.0  360.0
3   2026-06-01           Hosomaki ŁOSOŚ SUROWY | 8 szt    3   25.0   75.0
4   2026-06-01         Futomaki TUŃCZYK SUROWY | 6 szt    2   45.0   90.0
..         ...                                     ...  ...    ...    ...
179 2026-06-07                Miso z łososiem | 350 ml    1   35.0   35.0
180 2026-06-07           Futomaki FIRE HARMONY | 6 szt    1   58.0   58.0
181 2026-06-07                Hosomaki AWOKADO | 8 szt    1   21.0   21.0
182 2026-06-07           Futomaki ŁOSOŚ SUROWY | 6 szt    1   38.0   38.0
183 2026-06-07  Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt    1   36.0   36.0

[162 rows x 5 columns]

In [89]:
sales.dtypes

date     datetime64[us]
name                str
qty               int64
price           float64
sum             float64
dtype: object

In [90]:
sorted(sales['name'].unique())

['Amour Set | 36 szt',
 'Atlantic Wave roll | 8 szt',
 'Black dragon roll | 8 szt',
 'California KRAB-MIX | 8 szt',
 'California KREWETKA GOTOWANA | 8 szt',
 'California RAINBOW | 8 szt',
 'California TUŃCZYK SUROWY | 8 szt',
 'California z czarnym ryżem ŁOSOŚ SUROWY | 8 szt',
 'Cheese philadelphia | 8 szt',
 'Duo set | 28 szt',
 'Fanta jagoda 0.33l',
 'Feliks roll | 8 szt',
 'Fuji roll | 8 szt',
 'Futomaki AWOKADO | 6 szt',
 'Futomaki FIRE HARMONY | 6 szt',
 'Futomaki FRESH ROLL | 6 szt',
 'Futomaki KALMAR PANKO | 6 szt',
 'Futomaki KRAB W TEMPURZE | 6 szt',
 'Futomaki KREWETKA EBI | 6 szt / 12 szt',
 'Futomaki KREWETKA PANKO | 6 szt / 12 szt',
 'Futomaki TUŃCZYK SUROWY | 6 szt',
 'Futomaki TUŃCZYK SUROWY | 6 szt / 12 szt',
 'Futomaki WARZYWA W TEMPURZE | 6 szt',
 'Futomaki ŁOSOŚ GRILLOWANY | 6 szt',
 'Futomaki ŁOSOŚ GRILLOWANY | 6 szt / 12 szt',
 'Futomaki ŁOSOŚ SUROWY | 6 szt',
 'Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt',
 'Green dragon roll | 8 szt',
 'Grill set | 30 szt',
 'Gunkan Ebi | 2 szt',
 'Gunkan ŁOSOŚ SUROWY | 2 szt',
 'Hosomaki AWOKADO | 8 szt',
 'Hosomaki KANPYO | 8 szt',
 'Hosomaki KREWETKA EBI | 8 szt',
 'Hosomaki KREWETKA PANKO | 8 szt',
 'Hosomaki MANGO | 8 szt',
 'Hosomaki OGÓREK | 8 szt',
 'Hosomaki ŁOSOŚ GRILLOWANY | 8 szt',
 'Hosomaki ŁOSOŚ SUROWY | 8 szt',
 'Krabs - Burger',
 'Krewetki w tempurze | 6 szt',
 'Kurama set | 20 szt',
 'Miso inari tofu | 350 ml',
 'Miso z krewetkami | 350 ml',
 'Miso z łososiem | 350 ml',
 'Miyagi set | 30 szt',
 'Nigiri awokado | 2 szt',
 'Nigiri ŁOSOŚ | 2 szt',
 'Nigiri łosoś grillowany | 2 szt',
 'Nigiri łosoś | 2 szt',
 'PROMO 1+1=3 Sushi burgery',
 'Pałeczki',
 'Philadelphia grill | 8 szt',
 'Philadelphia mix | 8 szt',
 'Philadelphia tuńczyk | 8 szt',
 'Philadelphia łosoś | 8 szt',
 'Red alert roll | 8 szt',
 'Rolka w tempurze KREWETKA EBI | 8 szt',
 'Rolka w tempurze ŁOSOŚ GRILLOWANY | 8 szt',
 'Rolka w tempurze ŁOSOŚ SUROWY | 8 szt',
 'Samurai roll | 8 szt',
 'Sałatka wakame',
 'Sos sojowy 30ml',
 'Sos spicy majo 30ml',
 'Sos teriyaki 30ml',
 'Sos unagi',
 'Sos unagi 30ml',
 'Sos śliwkowy 30ml',
 'Sushi burger KREWETKA GOTOWANA',
 'Sushi burger KREWETKA PANKO',
 'Sushi burger WEGE',
 'Sushi burger ŁOSOŚ GRILLOWANY',
 'Sushi burger ŁOSOŚ SUROWY',
 'Tiger roll | 8 szt',
 'Tokyo roll | 8 szt',
 'Vibe roll ŁOSOŚ SUROWY | 8 szt',
 'Wege set | 38 szt',
 'Yakuza roll | 8 szt',
 'Zapieczona rolka FELIX | 8 szt (NOWOŚĆ)',
 'Zestaw "Premium sake" | 38 szt',
 'Zestaw Amour | 36 szt',
 'Zestaw Duo | 28 szt',
 'Zestaw Grill | 30 szt',
 'Zestaw Hosomaki | 56 szt',
 'Zestaw Miyagi | 30 szt',
 'Zestaw Philadelphia + Krabs Burger -50%',
 'Zestaw Philadelphia | 24 szt',
 'Zestaw Sakura | 62 szt',
 'Zestaw Startowy | 16 szt',
 'Zestaw Vibe | 32 szt']

### Import data (margin_table)

In [91]:
margin = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / 'margin_table.csv')
margin.head(10)

,ПОЗИЦИЯ,КАТЕГОРИЯ,СОСТОЯНИЕ,РЕСТ,РАСХОДЫ,VAT ПРОЦ,ОФЕР 25%,НОВАЯ ЦЕНА,ЦЕНА БРУТТО,ЦЕНА ОДБЮР,...,FC,ОФЕР_Д,БРУТТО_Д,ПРОВИЗИЯ_Д,VAT 8%_Д,ПОЛУЧАЕМ ОТ НИХ_Д,ЧИСТЯК_Д,ПРОФИТ_Д,МАРЖА_Д,FC_Д
0,Miso krewetki,ZUPY,Активно,Vibe,5.45,23.0,26.79,22.0,27.0,24.3,...,29.1%,35.39,40.0,16.00,3.20,24.00,20.80,15.35,73.82%,26.18%
1,Miso łosoś,ZUPY,Активно,Vibe,3.59,8.0,15.50,NaN,27.0,24.3,...,16.0%,23.32,30.0,12.00,2.40,18.00,15.60,12.01,77.00%,23.00%
2,Miso inari tofu,ZUPY,Активно,Vibe,1.51,8.0,6.52,NaN,25.0,22.5,...,7.3%,9.81,11.0,4.40,0.88,6.60,5.72,4.21,73.62%,26.38%
3,Promo set | 10 szt PROMO,ZESTAWY,Активно,Rice,14.93,8.0,45.94,NaN,0.0,0.0,...,NaN,97.02,70.0,28.00,5.60,42.00,36.40,21.47,58.99%,41.01%
4,NESUROWE set | 10 szt PROMO,ZESTAWY,Активно,Rice,15.27,8.0,46.99,NaN,0.0,0.0,...,NaN,99.24,70.0,28.00,5.60,42.00,36.40,21.13,58.06%,41.94%
5,Zestaw Phila | 16 szt,ZESTAWY,Активно,Rice,18.21,8.0,56.05,65.0,64.6,64.6,...,30.6%,118.37,89.6,35.84,7.17,53.76,46.59,28.38,60.91%,39.09%
6,Studencki | 32 szt,ZESTAWY,Активно,Rice,18.90,8.0,58.18,68.0,65.6,65.6,...,31.3%,122.87,91.6,36.64,7.33,54.96,47.63,28.73,60.31%,39.69%
7,Zestaw Hosomaki | 40 szt,ZESTAWY,Активно,Rice,20.57,8.0,63.32,74.0,74.6,74.6,...,30.0%,133.71,103.6,41.44,8.29,62.16,53.87,33.30,61.82%,38.18%
8,Akira | 24 szt,ZESTAWY,Активно,Rice,24.99,8.0,76.93,90.0,89.6,89.6,...,30.3%,162.45,124.6,49.84,9.97,74.76,64.79,39.80,61.43%,38.57%
9,Tokio | 28 szt,ZESTAWY,Активно,Rice,25.50,8.0,78.49,92.0,91.6,91.6,...,30.3%,165.76,127.6,51.04,10.21,76.56,66.35,40.85,61.57%,38.43%

In [92]:
margin.columns

Index(['ПОЗИЦИЯ', 'КАТЕГОРИЯ', 'СОСТОЯНИЕ', 'РЕСТ', 'РАСХОДЫ', 'VAT ПРОЦ',
       'ОФЕР 25%', 'НОВАЯ ЦЕНА', 'ЦЕНА БРУТТО', 'ЦЕНА ОДБЮР', 'VAT',
       'ЦЕНА НЕТТО', 'ПРОФИТ', 'МАРЖА', 'FC', 'ОФЕР_Д', 'БРУТТО_Д',
       'ПРОВИЗИЯ_Д', 'VAT 8%_Д', 'ПОЛУЧАЕМ ОТ НИХ_Д', 'ЧИСТЯК_Д', 'ПРОФИТ_Д',
       'МАРЖА_Д', 'FC_Д'],
      dtype='str')

### Clean margin_table

In [93]:
margin = margin[margin['РЕСТ'] == 'Vibe']

In [94]:
margin = margin[['ПОЗИЦИЯ', 'КАТЕГОРИЯ', 'РАСХОДЫ', 'ЦЕНА БРУТТО', 'ПРОФИТ', 'МАРЖА', 'FC']]

In [95]:
margin

,ПОЗИЦИЯ,КАТЕГОРИЯ,РАСХОДЫ,ЦЕНА БРУТТО,ПРОФИТ,МАРЖА,FC
0,Miso krewetki,ZUPY,5.45,27.0,13.27,70.90%,29.1%
1,Miso łosoś,ZUPY,3.59,27.0,18.77,83.95%,16.0%
2,Miso inari tofu,ZUPY,1.51,25.0,19.19,92.71%,7.3%
20,Zestaw startowy | 16 szt,ZESTAWY,20.13,81.9,47.68,70.31%,29.7%
21,Hosomaki set | 56 szt,ZESTAWY,23.48,100.0,59.32,71.64%,28.4%
...,...,...,...,...,...,...,...
215,Shrimp Bowl,BOWL,14.75,50.0,19.90,57.44%,42.6%
216,Crunch tempura Bowl,BOWL,14.99,52.0,21.05,58.40%,41.6%
217,Phila KRAB-MIX,PHILADELPHIA,12.66,55.0,32.88,72.21%,27.8%
218,Miso ramen,RAMEN,12.71,45.0,24.55,65.89%,34.1%
219,Tantamen ramen,RAMEN,18.48,55.0,27.06,59.42%,40.6%

In [96]:
margin = margin.rename(columns={
    'ПОЗИЦИЯ': 'name',
    'КАТЕГОРИЯ': 'category',
    'РАСХОДЫ': 'excpenses',
    'ЦЕНА БРУТТО': 'price_gross',
    'ПРОФИТ': 'unit_profit',
    'МАРЖА': 'marginal_profit',
    'FC': 'food_cost'
})

In [97]:
margin.sort_values(by='name', axis=0)

,name,category,excpenses,price_gross,unit_profit,marginal_profit,food_cost
111,Akami Tamago roll,ROLKI AUTORSKIE,13.43,50.0,27.97,67.55%,32.5%
104,Atlantic Wave,ROLKI AUTORSKIE,13.87,60.0,27.71,66.65%,33.4%
116,Awokado delux,ROLKI AUTORSKIE,12.37,55.0,33.17,72.84%,27.2%
38,Awokado fresh roll,WEGE MENU,9.53,38.0,21.93,69.71%,30.3%
60,B. Wege,SUSHI BURGER,8.54,50.0,32.86,79.38%,20.6%
...,...,...,...,...,...,...,...
74,ZR Krewetki,ROLKI ZAPIECZONE,13.31,60.0,28.27,67.99%,32.0%
77,ZR Surowy,ROLKI ZAPIECZONE,12.11,60.0,37.57,75.62%,24.4%
79,ZR Łosoś pieczony,ROLKI ZAPIECZONE,10.58,60.0,39.10,78.70%,21.3%
27,Zestaw Amour | 36 szt,ZESTAWY,42.75,195.0,118.71,73.52%,26.5%
20,Zestaw startowy | 16 szt,ZESTAWY,20.13,81.9,47.68,70.31%,29.7%

In [98]:
sorted(margin['name'].unique())

['Akami Tamago roll',
 'Atlantic Wave',
 'Awokado delux',
 'Awokado fresh roll',
 'B. Wege',
 'Black Philadelphia',
 'Black dragon roll',
 'Bonito roll',
 'Burger czarny ryż KREWETKA GOTOWANA',
 'Burger grill łosoś',
 'Burger krewetka panko',
 'Burger łosoś surowy',
 'C Black Surowy',
 'Calif LOSOS I SEZAM',
 'Calif krewetka 16/20',
 'California GRILL',
 'California KRAB',
 'California KREW PANKO',
 'California RAINBOW',
 'California SHIITAKE',
 'California SUROWY',
 'California TUNA',
 'California Warzywa w tempurze',
 'Canada roll',
 'Cheddar roll',
 'Crunch tempura Bowl',
 'Duo set | 28 szt',
 'Feliks łosoś',
 'Fibonacci roll',
 'Fuji roll',
 'Futo AWOKADO',
 'Futo EBI',
 'Futo FIRE HARMONY',
 'Futo FRESH ROLL',
 'Futo GRILL',
 'Futo KALMAR TEMPURA',
 'Futo KRAB TEMPURA',
 'Futo KREWETKA TEMPURA',
 'Futo MANGO',
 'Futo SHIITAKE',
 'Futo SUROWY',
 'Futo TATAR',
 'Futo TUNA',
 'Futo WARZYWA TEMPURA',
 'Futo ŁOSOŚ TEMPURA',
 'Futomaki set | 48 szt',
 'Green dragon roll',
 'Green fresh roll',
 'Grill set | 30 szt',
 'Gunk Ebi',
 'Gunk Maguro',
 'Gunk Łosoś',
 'Hikari set | 48 szt',
 'Hoso awokado',
 'Hoso grill',
 'Hoso kanpyo',
 'Hoso krew panko',
 'Hoso krewetka',
 'Hoso mango',
 'Hoso ogórek',
 'Hoso oshinko',
 'Hoso serek',
 'Hoso surowy',
 'Hoso tuna',
 'Hosomaki set | 56 szt',
 'Itsuki set | 24 szt',
 'Krabs-burger',
 'Kurama set | 20 szt',
 'Miso inari tofu',
 'Miso krewetki',
 'Miso ramen',
 'Miso łosoś',
 'Misora set | 32 szt + napój',
 'Miyagi set | 30 szt',
 'Nigiri awokado',
 'Nigiri ebi',
 'Nigiri tuna',
 'Nigiri unagi',
 'Nigiri łosoś',
 'Ocean roll',
 'PRZ Kalmar panko',
 'PRZ Krewetki w tempurze',
 'Phila CHEDDAR',
 'Phila CHEESE',
 'Phila EBI',
 'Phila GRILL',
 'Phila KRAB-MIX',
 'Phila TUNA',
 'Phila WĘGORZ',
 'Phila ŁOSOŚ',
 'Philadelia MIX',
 'Philadelphia | 24 szt',
 'Premium sake set | 38 szt',
 'Promo 1 + 1 SOBAKI VIBE',
 'Promo Burger 1+1',
 'RT Ebi',
 'RT Grill',
 'RT Hoso GRILL',
 'RT Surowy',
 'Red Dragon roll',
 'Red allert roll',
 'SD Grill + wakame',
 'SD MR_KRABS',
 'SD kalmar + tatar',
 'Saga roll',
 'Sakura set | 62 szt',
 'Salmon wakame Bowl',
 'Shrimp Bowl',
 'Sunrise roll',
 'Sushi dog SHIITAKE',
 'Takumi roll',
 'Tantamen ramen',
 'Tempura fusion roll',
 'Tiger roll',
 'Tokyo roll',
 'Vibe Roll Krewetka',
 'Vibe set | 32 szt',
 'Wakame',
 'Wege set | 44 szt',
 'Yakuza roll',
 'Yami set | 38 szt (Black Friday)',
 'ZR Felix',
 'ZR Krab',
 'ZR Krewetka Ebi & Mango',
 'ZR Krewetka panko',
 'ZR Krewetki',
 'ZR Surowy',
 'ZR Łosoś pieczony',
 'Zestaw Amour | 36 szt',
 'Zestaw startowy | 16 szt']

In [99]:
mapping_df = pd.DataFrame({
    'sales_name': sorted(sales['name'].unique()),
    'margin_name': '',
    'match_type': '',
    'reviewed': False
})

In [100]:
mapping_df

                                 sales_name margin_name match_type  reviewed
0                        Amour Set | 36 szt                            False
1                Atlantic Wave roll | 8 szt                            False
2                 Black dragon roll | 8 szt                            False
3               California KRAB-MIX | 8 szt                            False
4      California KREWETKA GOTOWANA | 8 szt                            False
..                                      ...         ...        ...       ...
85  Zestaw Philadelphia + Krabs Burger -50%                            False
86             Zestaw Philadelphia | 24 szt                            False
87                   Zestaw Sakura | 62 szt                            False
88                 Zestaw Startowy | 16 szt                            False
89                     Zestaw Vibe | 32 szt                            False

[90 rows x 4 columns]

In [101]:
# mapping_df.to_csv(Path.cwd().parent / 'data' / 'mappings' / 'product_name_mapping.csv', index=False)

In [102]:
# margin.to_csv(Path.cwd().parent / 'data' / 'mappings' / 'margin_table.csv', index=False)

In [103]:
margin

,name,category,excpenses,price_gross,unit_profit,marginal_profit,food_cost
0,Miso krewetki,ZUPY,5.45,27.0,13.27,70.90%,29.1%
1,Miso łosoś,ZUPY,3.59,27.0,18.77,83.95%,16.0%
2,Miso inari tofu,ZUPY,1.51,25.0,19.19,92.71%,7.3%
20,Zestaw startowy | 16 szt,ZESTAWY,20.13,81.9,47.68,70.31%,29.7%
21,Hosomaki set | 56 szt,ZESTAWY,23.48,100.0,59.32,71.64%,28.4%
...,...,...,...,...,...,...,...
215,Shrimp Bowl,BOWL,14.75,50.0,19.90,57.44%,42.6%
216,Crunch tempura Bowl,BOWL,14.99,52.0,21.05,58.40%,41.6%
217,Phila KRAB-MIX,PHILADELPHIA,12.66,55.0,32.88,72.21%,27.8%
218,Miso ramen,RAMEN,12.71,45.0,24.55,65.89%,34.1%
219,Tantamen ramen,RAMEN,18.48,55.0,27.06,59.42%,40.6%

In [104]:
sales

          date                                    name  qty  price    sum
0   2026-06-01       Futomaki ŁOSOŚ GRILLOWANY | 6 szt    6   38.0  228.0
1   2026-06-01                    Nigiri łosoś | 2 szt    4   25.0  100.0
2   2026-06-01               PROMO 1+1=3 Sushi burgery    3  120.0  360.0
3   2026-06-01           Hosomaki ŁOSOŚ SUROWY | 8 szt    3   25.0   75.0
4   2026-06-01         Futomaki TUŃCZYK SUROWY | 6 szt    2   45.0   90.0
..         ...                                     ...  ...    ...    ...
179 2026-06-07                Miso z łososiem | 350 ml    1   35.0   35.0
180 2026-06-07           Futomaki FIRE HARMONY | 6 szt    1   58.0   58.0
181 2026-06-07                Hosomaki AWOKADO | 8 szt    1   21.0   21.0
182 2026-06-07           Futomaki ŁOSOŚ SUROWY | 6 szt    1   38.0   38.0
183 2026-06-07  Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt    1   36.0   36.0

[162 rows x 5 columns]

In [117]:
mapping = pd.read_csv(Path().cwd().parent / 'data' / 'mappings' / 'product_name_mapping.csv')
mapping = mapping[['sales_name', 'margin_name']]
mapping

,sales_name,margin_name
0,Amour Set | 36 szt,Zestaw Amour | 36 szt
1,Atlantic Wave roll | 8 szt,Atlantic Wave
2,Black dragon roll | 8 szt,Black dragon roll
3,California KRAB-MIX | 8 szt,California KRAB
4,California KREWETKA GOTOWANA | 8 szt,Calif krewetka 16/20
...,...,...
85,Zestaw Philadelphia + Krabs Burger -50%,Zestaw Philadelphia + Krabs Burger -50%
86,Zestaw Philadelphia | 24 szt,Philadelphia | 24 szt
87,Zestaw Sakura | 62 szt,Sakura set | 62 szt
88,Zestaw Startowy | 16 szt,Zestaw startowy | 16 szt
89,Zestaw Vibe | 32 szt,Vibe set | 32 szt

In [118]:
margin_table = pd.read_csv(Path().cwd().parent / 'data' / 'mappings' / 'margin_table.csv')

In [119]:
margin_table

,name,category,excepnses,price_gross,unit_profit,marginal_profit,food_cost
0,Miso krewetki,ZUPY,5.45,27.0,13.27,70.90%,29.1%
1,Miso łosoś,ZUPY,3.59,27.0,18.77,83.95%,16.0%
2,Miso inari tofu,ZUPY,1.51,25.0,19.19,92.71%,7.3%
3,Zestaw startowy | 16 szt,ZESTAWY,20.13,81.9,47.68,70.31%,29.7%
4,Hosomaki set | 56 szt,ZESTAWY,23.48,100.0,59.32,71.64%,28.4%
...,...,...,...,...,...,...,...
126,Crunch tempura Bowl,BOWL,14.99,52.0,21.05,58.40%,41.6%
127,Phila KRAB-MIX,PHILADELPHIA,12.66,55.0,32.88,72.21%,27.8%
128,Miso ramen,RAMEN,12.71,45.0,24.55,65.89%,34.1%
129,Tantamen ramen,RAMEN,18.48,55.0,27.06,59.42%,40.6%
130,Zestaw Philadelphia + Krabs Burger -50%,SUSHI BURGER,50.30,170.0,90.46,64.26%,35.7%

In [121]:
mapping_matched = mapping[mapping['margin_name'].notna() & mapping['margin_name'].ne('')].copy()

In [123]:
mapping_matched

,sales_name,margin_name
0,Amour Set | 36 szt,Zestaw Amour | 36 szt
1,Atlantic Wave roll | 8 szt,Atlantic Wave
2,Black dragon roll | 8 szt,Black dragon roll
3,California KRAB-MIX | 8 szt,California KRAB
4,California KREWETKA GOTOWANA | 8 szt,Calif krewetka 16/20
...,...,...
85,Zestaw Philadelphia + Krabs Burger -50%,Zestaw Philadelphia + Krabs Burger -50%
86,Zestaw Philadelphia | 24 szt,Philadelphia | 24 szt
87,Zestaw Sakura | 62 szt,Sakura set | 62 szt
88,Zestaw Startowy | 16 szt,Zestaw startowy | 16 szt
89,Zestaw Vibe | 32 szt,Vibe set | 32 szt

In [125]:
margin_by_sales_name = mapping_matched.merge(
    right=margin_table.rename(columns={'name': 'margin_table_name'}),
    left_on='margin_name',
    right_on='margin_table_name',
    how='left',
    validate='many_to_one'
)

In [126]:
margin_by_sales_name

,sales_name,margin_name,margin_table_name,category,excepnses,price_gross,unit_profit,marginal_profit,food_cost
0,Amour Set | 36 szt,Zestaw Amour | 36 szt,Zestaw Amour | 36 szt,ZESTAWY,42.75,195.0,118.71,73.52%,26.5%
1,Atlantic Wave roll | 8 szt,Atlantic Wave,Atlantic Wave,ROLKI AUTORSKIE,13.87,60.0,27.71,66.65%,33.4%
2,Black dragon roll | 8 szt,Black dragon roll,Black dragon roll,ROLKI AUTORSKIE,18.29,70.0,39.67,68.44%,31.6%
3,California KRAB-MIX | 8 szt,California KRAB,California KRAB,CALIFORNIA,7.71,45.0,29.55,79.30%,20.7%
4,California KREWETKA GOTOWANA | 8 szt,Calif krewetka 16/20,Calif krewetka 16/20,CALIFORNIA,15.05,60.0,26.53,63.80%,36.2%
...,...,...,...,...,...,...,...,...,...
75,Zestaw Philadelphia + Krabs Burger -50%,Zestaw Philadelphia + Krabs Burger -50%,Zestaw Philadelphia + Krabs Burger -50%,SUSHI BURGER,50.30,170.0,90.46,64.26%,35.7%
76,Zestaw Philadelphia | 24 szt,Philadelphia | 24 szt,Philadelphia | 24 szt,ZESTAWY,38.04,170.0,102.72,72.98%,27.0%
77,Zestaw Sakura | 62 szt,Sakura set | 62 szt,Sakura set | 62 szt,ZESTAWY,69.78,295.0,174.48,71.43%,28.6%
78,Zestaw Startowy | 16 szt,Zestaw startowy | 16 szt,Zestaw startowy | 16 szt,ZESTAWY,20.13,81.9,47.68,70.31%,29.7%
79,Zestaw Vibe | 32 szt,Vibe set | 32 szt,Vibe set | 32 szt,ZESTAWY,50.77,200.0,114.83,69.34%,30.7%

In [127]:
columns_to_add = [
    'sales_name',
    'unit_profit',
    'marginal_profit',
    'food_cost'
]

In [128]:
sales_final = sales.merge(
    right=margin_by_sales_name[columns_to_add],
    left_on='name',
    right_on='sales_name',
    how='left',
    validate='many_to_one'
)

In [129]:
sales_final

,date,name,qty,price,sum,sales_name,unit_profit,marginal_profit,food_cost
0,2026-06-01,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,38.0,228.0,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,21.47,74.10%,25.9%
1,2026-06-01,Nigiri łosoś | 2 szt,4,25.0,100.0,Nigiri łosoś | 2 szt,15.88,73.77%,26.2%
2,2026-06-01,PROMO 1+1=3 Sushi burgery,3,120.0,360.0,PROMO 1+1=3 Sushi burgery,64.00,64.42%,35.6%
3,2026-06-01,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,25.0,75.0,Hosomaki ŁOSOŚ SUROWY | 8 szt,15.52,72.09%,27.9%
4,2026-06-01,Futomaki TUŃCZYK SUROWY | 6 szt,2,45.0,90.0,Futomaki TUŃCZYK SUROWY | 6 szt,21.80,71.16%,28.8%
...,...,...,...,...,...,...,...,...,...
157,2026-06-07,Miso z łososiem | 350 ml,1,35.0,35.0,Miso z łososiem | 350 ml,18.77,83.95%,16.0%
158,2026-06-07,Futomaki FIRE HARMONY | 6 szt,1,58.0,58.0,Futomaki FIRE HARMONY | 6 szt,21.87,67.14%,32.9%
159,2026-06-07,Hosomaki AWOKADO | 8 szt,1,21.0,21.0,Hosomaki AWOKADO | 8 szt,13.49,74.04%,26.0%
160,2026-06-07,Futomaki ŁOSOŚ SUROWY | 6 szt,1,38.0,38.0,Futomaki ŁOSOŚ SUROWY | 6 szt,21.17,73.06%,26.9%
161,2026-06-07,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,36.0,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,21.17,73.06%,26.9%

In [130]:
sales_final = sales_final.drop(columns='sales_name')

In [131]:
sales_final

,date,name,qty,price,sum,unit_profit,marginal_profit,food_cost
0,2026-06-01,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,38.0,228.0,21.47,74.10%,25.9%
1,2026-06-01,Nigiri łosoś | 2 szt,4,25.0,100.0,15.88,73.77%,26.2%
2,2026-06-01,PROMO 1+1=3 Sushi burgery,3,120.0,360.0,64.00,64.42%,35.6%
3,2026-06-01,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,25.0,75.0,15.52,72.09%,27.9%
4,2026-06-01,Futomaki TUŃCZYK SUROWY | 6 szt,2,45.0,90.0,21.80,71.16%,28.8%
...,...,...,...,...,...,...,...,...
157,2026-06-07,Miso z łososiem | 350 ml,1,35.0,35.0,18.77,83.95%,16.0%
158,2026-06-07,Futomaki FIRE HARMONY | 6 szt,1,58.0,58.0,21.87,67.14%,32.9%
159,2026-06-07,Hosomaki AWOKADO | 8 szt,1,21.0,21.0,13.49,74.04%,26.0%
160,2026-06-07,Futomaki ŁOSOŚ SUROWY | 6 szt,1,38.0,38.0,21.17,73.06%,26.9%
161,2026-06-07,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,36.0,21.17,73.06%,26.9%

In [134]:
sales_final[sales_final['unit_profit'].isna()]['name'].drop_duplicates()

11               Samurai roll | 8 szt
67                          Sos unagi
70                Sos spicy majo 30ml
71                     Sos unagi 30ml
84                           Pałeczki
100                Fanta jagoda 0.33l
102                 Sos teriyaki 30ml
144                 Sos śliwkowy 30ml
150    Vibe roll ŁOSOŚ SUROWY | 8 szt
156                   Sos sojowy 30ml
Name: name, dtype: str