In [8]:
import pandas as pd
from pathlib import Path

In [ ]:
path_1 = Path()

In [12]:
df_01_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.01.csv')
df_02_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.02.csv')
df_03_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.03.csv')
df_04_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.04.csv')
df_05_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.05.csv')
df_06_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.06.csv')
df_07_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.07.csv')

In [13]:
df_01_06['Период'] = '01.06.2026'
df_02_06['Период'] = '02.06.2026'
df_03_06['Период'] = '03.06.2026'
df_04_06['Период'] = '04.06.2026'
df_05_06['Период'] = '05.06.2026'
df_06_06['Период'] = '06.06.2026'
df_07_06['Период'] = '07.06.2026'

In [14]:
df_01_06.dtypes

Тип                     str
Название позиции        str
Продано               int64
Цена                float64
Период                  str
Location                str
dtype: object

In [15]:
dfs = [df_01_06, df_02_06, df_03_06, df_04_06, df_05_06, df_06_06, df_07_06]

In [16]:
df = pd.concat(dfs, ignore_index=True)

In [17]:
df

,Тип,Название позиции,Продано,Цена,Период,Location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI

In [22]:
df = df.rename(columns={
    'Тип': 'type',
    'Название позиции': 'name',
    'Продано': 'qty',
    'Цена': 'sum',
    'Период': 'date',
    'Location': 'location'
    })

In [23]:
df

,type,name,qty,sum,date,location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI