In [25]:
import pandas as pd
from pathlib import Path

### Import data from raw .csv files

In [26]:
df_01_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.01.csv')
df_02_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.02.csv')
df_03_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.03.csv')
df_04_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.04.csv')
df_05_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.05.csv')
df_06_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.06.csv')
df_07_06 = pd.read_csv(Path.cwd().parent / 'data' / 'raw' / '2026.06.07.csv')

In [27]:
df_01_06['Период'] = '01.06.2026'
df_02_06['Период'] = '02.06.2026'
df_03_06['Период'] = '03.06.2026'
df_04_06['Период'] = '04.06.2026'
df_05_06['Период'] = '05.06.2026'
df_06_06['Период'] = '06.06.2026'
df_07_06['Период'] = '07.06.2026'

In [28]:
df_01_06.dtypes

Тип                     str
Название позиции        str
Продано               int64
Цена                float64
Период                  str
Location                str
dtype: object

In [29]:
dfs = [df_01_06, df_02_06, df_03_06, df_04_06, df_05_06, df_06_06, df_07_06]

In [30]:
df = pd.concat(dfs, ignore_index=True)

In [31]:
df

,Тип,Название позиции,Продано,Цена,Период,Location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI

### Data cleaning (Sales Table)

In [32]:
df = df.rename(columns={
    'Тип': 'type',
    'Название позиции': 'name',
    'Продано': 'qty',
    'Цена': 'sum',
    'Период': 'date',
    'Location': 'location'
    })

In [33]:
df

,type,name,qty,sum,date,location
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026,VIBE SUSHI
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,01.06.2026,VIBE SUSHI
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,01.06.2026,VIBE SUSHI
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,01.06.2026,VIBE SUSHI
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,01.06.2026,VIBE SUSHI
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,07.06.2026,VIBE SUSHI
187,Дополнение,Wasabi,2,4.0,07.06.2026,VIBE SUSHI
188,Дополнение,Sos teriyaki 30ml,1,3.0,07.06.2026,VIBE SUSHI
189,Дополнение,Krabs - Burger,1,25.0,07.06.2026,VIBE SUSHI
190,Дополнение,6 szt,1,NaN,07.06.2026,VIBE SUSHI

In [34]:
df['price'] = df['sum'] / df['qty']

In [35]:
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')

In [36]:
df.dtypes

type                   str
name                   str
qty                  int64
sum                float64
date        datetime64[us]
location               str
price              float64
dtype: object

In [37]:
df

,type,name,qty,sum,date,location,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,VIBE SUSHI,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,VIBE SUSHI,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,VIBE SUSHI,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,VIBE SUSHI,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,VIBE SUSHI,45.0
...,...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,2026-06-07,VIBE SUSHI,1.5
187,Дополнение,Wasabi,2,4.0,2026-06-07,VIBE SUSHI,2.0
188,Дополнение,Sos teriyaki 30ml,1,3.0,2026-06-07,VIBE SUSHI,3.0
189,Дополнение,Krabs - Burger,1,25.0,2026-06-07,VIBE SUSHI,25.0
190,Дополнение,6 szt,1,NaN,2026-06-07,VIBE SUSHI,NaN

In [39]:
df = df.drop(labels=['location'], axis=1)

In [40]:
df

,type,name,qty,sum,date,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,45.0
...,...,...,...,...,...,...
186,Дополнение,Imbir,2,3.0,2026-06-07,1.5
187,Дополнение,Wasabi,2,4.0,2026-06-07,2.0
188,Дополнение,Sos teriyaki 30ml,1,3.0,2026-06-07,3.0
189,Дополнение,Krabs - Burger,1,25.0,2026-06-07,25.0
190,Дополнение,6 szt,1,NaN,2026-06-07,NaN

In [43]:
df = df[df['type'] != 'Дополнение']

In [44]:
df

,type,name,qty,sum,date,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,38.0
1,Позиция,Nigiri łosoś | 2 szt,4,100.0,2026-06-01,25.0
2,Позиция,PROMO 1+1=3 Sushi burgery,3,360.0,2026-06-01,120.0
3,Позиция,Hosomaki ŁOSOŚ SUROWY | 8 szt,3,75.0,2026-06-01,25.0
4,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt,2,90.0,2026-06-01,45.0
...,...,...,...,...,...,...
179,Позиция,Miso z łososiem | 350 ml,1,35.0,2026-06-07,35.0
180,Позиция,Futomaki FIRE HARMONY | 6 szt,1,58.0,2026-06-07,58.0
181,Позиция,Hosomaki AWOKADO | 8 szt,1,21.0,2026-06-07,21.0
182,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt,1,38.0,2026-06-07,38.0
183,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,2026-06-07,36.0

In [45]:
df = df[['date', 'name', 'qty', 'price', 'sum']]

In [46]:
df

          date                                    name  qty  price    sum
0   2026-06-01       Futomaki ŁOSOŚ GRILLOWANY | 6 szt    6   38.0  228.0
1   2026-06-01                    Nigiri łosoś | 2 szt    4   25.0  100.0
2   2026-06-01               PROMO 1+1=3 Sushi burgery    3  120.0  360.0
3   2026-06-01           Hosomaki ŁOSOŚ SUROWY | 8 szt    3   25.0   75.0
4   2026-06-01         Futomaki TUŃCZYK SUROWY | 6 szt    2   45.0   90.0
..         ...                                     ...  ...    ...    ...
179 2026-06-07                Miso z łososiem | 350 ml    1   35.0   35.0
180 2026-06-07           Futomaki FIRE HARMONY | 6 szt    1   58.0   58.0
181 2026-06-07                Hosomaki AWOKADO | 8 szt    1   21.0   21.0
182 2026-06-07           Futomaki ŁOSOŚ SUROWY | 6 szt    1   38.0   38.0
183 2026-06-07  Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt    1   36.0   36.0

[162 rows x 5 columns]

In [48]:
df.dtypes

date     datetime64[us]
name                str
qty               int64
price           float64
sum             float64
dtype: object