In [1]:
import pandas as pd
from pathlib import Path

In [2]:
def load_data(file_path: str) -> pd.DataFrame:
    frames = []
    try:
        for files in Path(file_path).glob('*.csv'):
            df = pd.read_csv(files)
            report_date = pd.to_datetime(files.stem, format='%Y.%m.%d')
            df['report_date'] = report_date
            frames.append(df)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return pd.DataFrame()

    return pd.concat(frames, ignore_index=False).sort_values(by='report_date', ignore_index=True)

In [3]:
raw_dir = Path.cwd().parent / 'data' / 'raw'

In [4]:
sales_raw = load_data(raw_dir)
sales_raw

,Тип,Название позиции,Продано,Цена,Период,Location,report_date
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,01.06.2026-01.06.2026,VIBE SUSHI,2026-06-01
1,Дополнение,6 szt,2,NaN,01.06.2026-01.06.2026,VIBE SUSHI,2026-06-01
2,Позиция,Philadelphia tuńczyk | 8 szt,1,82.0,01.06.2026-01.06.2026,VIBE SUSHI,2026-06-01
3,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt / 12 szt,1,38.0,01.06.2026-01.06.2026,VIBE SUSHI,2026-06-01
4,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,01.06.2026-01.06.2026,VIBE SUSHI,2026-06-01
...,...,...,...,...,...,...,...
186,Позиция,California KRAB-MIX | 8 szt,1,45.0,07.06.2026-07.06.2026,VIBE SUSHI,2026-06-07
187,Позиция,Sos śliwkowy 30ml,1,4.0,07.06.2026-07.06.2026,VIBE SUSHI,2026-06-07
188,Позиция,Zestaw Startowy | 16 szt,1,81.9,07.06.2026-07.06.2026,VIBE SUSHI,2026-06-07
189,Позиция,Gunkan Ebi | 2 szt,1,30.0,07.06.2026-07.06.2026,VIBE SUSHI,2026-06-07
190,Дополнение,6 szt,1,NaN,07.06.2026-07.06.2026,VIBE SUSHI,2026-06-07

In [5]:
sales = sales_raw[['Тип', 'Название позиции', 'Продано', 'Цена', 'report_date']].rename(columns={
    'Тип': 'type',
    'Название позиции': 'name',
    'Продано': 'qty',
    'Цена': 'sum',
    'report_date': 'date'
    })

In [6]:
sales

,type,name,qty,sum,date
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01
1,Дополнение,6 szt,2,NaN,2026-06-01
2,Позиция,Philadelphia tuńczyk | 8 szt,1,82.0,2026-06-01
3,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt / 12 szt,1,38.0,2026-06-01
4,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,2026-06-01
...,...,...,...,...,...
186,Позиция,California KRAB-MIX | 8 szt,1,45.0,2026-06-07
187,Позиция,Sos śliwkowy 30ml,1,4.0,2026-06-07
188,Позиция,Zestaw Startowy | 16 szt,1,81.9,2026-06-07
189,Позиция,Gunkan Ebi | 2 szt,1,30.0,2026-06-07
190,Дополнение,6 szt,1,NaN,2026-06-07

In [7]:
sales['price'] = sales['sum'] / sales['qty']

In [8]:
sales['date'] = pd.to_datetime(sales['date'], format='%d.%m.%Y')

In [9]:
sales

,type,name,qty,sum,date,price
0,Позиция,Futomaki ŁOSOŚ GRILLOWANY | 6 szt,6,228.0,2026-06-01,38.0
1,Дополнение,6 szt,2,NaN,2026-06-01,NaN
2,Позиция,Philadelphia tuńczyk | 8 szt,1,82.0,2026-06-01,82.0
3,Позиция,Futomaki TUŃCZYK SUROWY | 6 szt / 12 szt,1,38.0,2026-06-01,38.0
4,Позиция,Futomaki ŁOSOŚ SUROWY | 6 szt / 12 szt,1,36.0,2026-06-01,36.0
...,...,...,...,...,...,...
186,Позиция,California KRAB-MIX | 8 szt,1,45.0,2026-06-07,45.0
187,Позиция,Sos śliwkowy 30ml,1,4.0,2026-06-07,4.0
188,Позиция,Zestaw Startowy | 16 szt,1,81.9,2026-06-07,81.9
189,Позиция,Gunkan Ebi | 2 szt,1,30.0,2026-06-07,30.0
190,Дополнение,6 szt,1,NaN,2026-06-07,NaN

In [ ]:
sales = sales[sales['type'] != 'Дополнение']

In [ ]:
sales

In [ ]:
sales = sales[['date', 'name', 'qty', 'price', 'sum']]

In [ ]:
sales

In [ ]:
sorted(sales['name'].unique())

In [ ]:
margin = pd.read_csv(Path.cwd().parent / 'data' / 'margin_table.csv')
margin.head(10)

In [ ]:
margin.columns

In [ ]:
margin = margin[margin['РЕСТ'] == 'Vibe']

In [ ]:
margin = margin[['ПОЗИЦИЯ', 'КАТЕГОРИЯ', 'РАСХОДЫ', 'ЦЕНА БРУТТО', 'ПРОФИТ', 'МАРЖА', 'FC', 'VAT', 'VAT ПРОЦ']]

In [ ]:
margin

In [ ]:
margin = margin.rename(columns={
    'ПОЗИЦИЯ': 'name',
    'КАТЕГОРИЯ': 'category',
    'РАСХОДЫ': 'unit_cost',
    'ЦЕНА БРУТТО': 'price_gross',
    'ПРОФИТ': 'unit_profit',
    'МАРЖА': 'marginal_profit',
    'FC': 'food_cost',
    'VAT': 'vat_as_cost',
    'VAT ПРОЦ': 'vat_rate'
})

In [ ]:
margin.sort_values(by='name', axis=0)

In [ ]:
sorted(margin['name'].unique())

In [ ]:
mapping_df = pd.DataFrame({'sales_name': sorted(sales['name'].unique())})

In [ ]:
mapping_df

In [ ]:
# mapping_df.to_csv(Path.cwd().parent / 'data' / 'mappings' / 'product_name_mapping.csv', index=False)

In [ ]:
margin.to_csv(Path.cwd().parent / 'data' / 'mappings' / 'margin_table.csv', index=False)

In [ ]:
margin

In [ ]:
sales

In [ ]:
mapping = pd.read_csv(Path().cwd().parent / 'data' / 'mappings' / 'product_name_mapping.csv')
mapping = mapping[['sales_name', 'margin_name']]
mapping

In [ ]:
margin_table = pd.read_csv(Path().cwd().parent / 'data' / 'mappings' / 'margin_table.csv')

In [ ]:
margin_table

In [ ]:
mapping_matched = mapping[mapping['margin_name'].notna() & mapping['margin_name'].ne('')].copy()

In [ ]:
mapping_matched

In [ ]:
margin_by_sales_name = mapping_matched.merge(
    right=margin_table.rename(columns={'name': 'margin_table_name'}),
    left_on='margin_name',
    right_on='margin_table_name',
    how='left',
    validate='many_to_one'
)

In [ ]:
margin_by_sales_name = margin_by_sales_name.rename({'excepnses': 'unit_cost'}, axis=1)

In [ ]:
margin_by_sales_name

In [ ]:
columns_to_add = [
    'sales_name',
    'unit_profit',
    'unit_cost',
    'marginal_profit',
    'food_cost',
    'vat_as_cost',
    'vat_rate',
]

In [ ]:
sales_final = sales.merge(
    right=margin_by_sales_name[columns_to_add],
    left_on='name',
    right_on='sales_name',
    how='left',
    validate='many_to_one'
)

In [ ]:
sales_final

In [ ]:
sales_final = sales_final.drop(columns='sales_name')

In [ ]:
sales_final

In [ ]:
sales_final = sales_final[['date', 'name', 'qty', 'price', 'vat_rate', 'unit_cost', 'vat_as_cost', 'unit_profit', 'marginal_profit', 'food_cost', 'sum']]

In [ ]:
sales_final = sales_final.rename({
    'price': 'unit_price',
    'food_cost': 'unit_food_cost',
    'sum': 'total_sum_of_sales_for_product'
}, axis=1)

In [ ]:
sales_final

In [ ]:
sales_final[sales_final['unit_profit'].isna()]['name'].drop_duplicates()

In [ ]:
sales_final[(sales_final['unit_price'] * sales_final['qty'] != sales_final['total_sum_of_sales_for_product'])]

In [ ]:
sales_final['total_cost'] = sales_final['unit_cost'] * sales_final['qty']

In [ ]:
sales_final

In [ ]:
sales_pivot = sales_final.groupby(by='name')[['qty', 'total_sum_of_sales_for_product', 'unit_price']].sum()
sales_pivot

In [ ]:
sales_pivot['price'] = sales_pivot['total_sum_of_sales_for_product'] / sales_pivot['qty']

In [ ]:
sales_pivot.sort_values(by='total_sum_of_sales_for_product', ascending=False).head(10)

In [ ]:
total_sales = sales_pivot['total_sum_of_sales_for_product'].sum()
total_sales

In [ ]:
sales_pivot['revenue_share_pct'] = sales_pivot['total_sum_of_sales_for_product'] / total_sales * 100
sales_pivot

In [ ]:
sales_pivot.sort_values(by='revenue_share_pct', ascending=False).head(10)['revenue_share_pct'].sum()

In [ ]:
sales_metrics = sales_final[['date', 'name', 'qty', 'unit_price', 'vat_rate', 'unit_cost']]
sales_metrics

In [ ]:
sales_metrics['unit_vat'] = sales_metrics['unit_price'] * sales_metrics['vat_rate'] / (100 + sales_metrics['vat_rate'])

In [ ]:
sales_metrics

In [ ]:
sales_metrics = sales_metrics.rename({'unit_price': 'unit_price_gross'}, axis=1)
sales_metrics

In [ ]:
sales_metrics['unit_price_net'] = sales_metrics['unit_price_gross'] - sales_metrics['unit_vat']
sales_metrics['unit_profit_est'] = sales_metrics['unit_price_net'] - sales_metrics['unit_cost']
sales_metrics['margin_rate'] = sales_metrics['unit_profit_est'] / sales_metrics['unit_price_net']
sales_metrics['food_cost_rate'] = sales_metrics['unit_cost'] / sales_metrics['unit_price_net']
sales_metrics['total_sales_net'] = sales_metrics['qty'] * sales_metrics['unit_price_net']
sales_metrics['total_sales_gross'] = sales_metrics['qty'] * sales_metrics['unit_price_gross']
sales_metrics['total_cost_est'] = sales_metrics['qty'] * sales_metrics['unit_cost']
sales_metrics['total_profit_est'] = sales_metrics['total_sales_net'] - sales_metrics['total_cost_est']

sales_metrics

In [ ]:
sales_metrics.dtypes

In [ ]:
sales_metrics = sales_metrics.dropna(axis=0)

In [ ]:
sales_metrics

In [ ]:
# sales_metrics.to_csv(Path.cwd().parent / 'data' / 'output' / 'sales_metrics.csv', index=False)

In [ ]:
sum(sales_metrics['total_profit_est'])